services:
  bank-service:
    build:
      context: .
      args:
        NUM_CUSTOMERS: ${NUM_CUSTOMERS}
        NUM_TRANSACTIONS: ${NUM_TRANSACTIONS}
        FED_INTEREST_RATE: ${FED_INTEREST_RATE}
        NDEBUG: ${NDEBUG}
        CONCURRENCY: ${CONCURRENCY}
        TEST_MODE: ${TEST_MODE}
    volumes:
      - ./records:/app/records
    environment:
      NUM_CUSTOMERS: ${NUM_CUSTOMERS}
      NUM_TRANSACTIONS: ${NUM_TRANSACTIONS}
    command: /bin/sh -c "./BankService.exe && touch /app/records/BANK_READY"
    healthcheck:
      test: ["CMD", "test", "-f", "/app/records/BANK_READY"]
      interval: 5s
      timeout: 3s
      retries: 5

  file-monitor:
    build: ./LightweightConsumer
    volumes:
      - ./records:/app/records
    environment:
      PYTHONUNBUFFERED: "1"
    command: /bin/sh -c "python file-processor.py"

  cleanup:
    image: alpine
    volumes:
      - .:/app
    working_dir: /app
    command: /bin/sh -c "rm -f BankService.exe *.o records/*/*.txt* records/*.SUCCESS records/BANK_READY"